- type: job
  id: QuadBorg
  name: job-name-quadborg
  description: job-description-quadborg
  playTimeTracker: JobBorgQuad
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hrs # Frontier: 10<12 hrs
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerQuadBorgBattery
  applyTraits: false