using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Shared._CD.Silicons;
using Content.Shared._CD.Silicons.Borgs;
using Content.Shared.Silicons.Borgs;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.IoC;

namespace Content.Client._CD.Silicons.Borgs.UI;

[GenerateTypedNameReferences]
public sealed partial class ChassisSpriteSelection : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IResourceCache _resource = default!;

    public BorgSubtypePrototype? SubtypePrototype;
    public event Action? SubtypeSelected;

    public const int PrototypeViewSize = 2;

    public ChassisSpriteSelection()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(BorgTypePrototype borgTypePrototype)
    {
        MainContainer.Visible = true;
        OptionsContainer.RemoveAllChildren();

        var buttonGroup = new ButtonGroup();
        List<Button> buttons = new()
        {
            CreateSubtypeButton(buttonGroup, borgTypePrototype.DummyPrototype, "Default", null)
        };

        foreach (var subtypePrototype in _proto.EnumeratePrototypes<BorgSubtypePrototype>())
        {
            if (subtypePrototype.ParentType != borgTypePrototype.ID)
                continue;

            buttons.Add(CreateSubtypeButton(
                buttonGroup,
                subtypePrototype.DummyPrototype,
                subtypePrototype.Name,
                subtypePrototype
            ));
        }

        foreach (var button in buttons)
        {
            OptionsContainer.AddChild(button);
        }
    }

    private Button CreateSubtypeButton(
        ButtonGroup group,
        EntProtoId dummyPrototype,
        string labelText,
        BorgSubtypePrototype? subtypePrototype
    )
    {
        var button = new Button
        {
            Group = group,
            VerticalAlignment = VAlignment.Bottom,
            MinHeight = 0,
            MinWidth = 0
        };

        button.OnPressed += _ =>
        {
            SubtypePrototype = subtypePrototype;
            SubtypeSelected?.Invoke();
        };

        var buttonContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(4, 4, 4, 4)
        };

        var prototypeView = CreateEntityPrototypeView(dummyPrototype);

        var imageViewport = new LayoutContainer
        {
            RectClipContent = true,
            MinHeight = 64,        
            MaxHeight = 100,
            MinWidth = 64
        };


        LayoutContainer.SetAnchorBottom(prototypeView, 1f);
        LayoutContainer.SetAnchorTop(prototypeView, 1f);
        LayoutContainer.SetAnchorLeft(prototypeView, 0.5f);
        LayoutContainer.SetAnchorRight(prototypeView, 0.5f);

        LayoutContainer.SetGrowVertical(prototypeView, LayoutContainer.GrowDirection.Begin);
        LayoutContainer.SetGrowHorizontal(prototypeView, LayoutContainer.GrowDirection.Both);

        imageViewport.AddChild(prototypeView);
        buttonContent.AddChild(imageViewport);

        buttonContent.AddChild(new Label { Text = labelText, HorizontalAlignment = HAlignment.Center });

        button.AddChild(buttonContent);

        return button;
    }

    private EntityPrototypeView CreateEntityPrototypeView(EntProtoId entProtoId)
    {
        var entPrototypeView = new EntityPrototypeView();

        entPrototypeView.SetPrototype(entProtoId);
        entPrototypeView.Scale *= PrototypeViewSize;
        

        return entPrototypeView;
    }
}