- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Atlast  # Atlas is missing in HL
  - Amber
  # - Bagel   # Disabled due to lowpop on Sandwich
  # - Box     # Disabled due to lowpop on Sandwich
  # - Cluster # Cluster is missing in HL
  # - Convex  # Disabled due to lowpop on Sandwich
  # - Core
  - Eaglerock
  - Elkridge
  # - Fland   # Disabled due to lowpop on Sandwich
  # - Gate
  - HardCore
  - HardlightSilica
  # - Loop    # Disabled due to Error occuring when creating
  # - Marathon # No HL version
  # - Meta    # Disabled due to Error occuring when creating
  # - Oasis   # Disabled due to lowpop on Sandwich
  - Omega   
  # - Packed  # Did HL even change this map at all???
  # - Plasma  # Disabled due to lowpop on Sandwich
  - Reach
  #- Train

# Gonna crash out, this is the pool we are using smh