using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class RandomizeProfileConfirmationWindow : DefaultWindow
{
    public event Action? OnConfirmed;

    public RandomizeProfileConfirmationWindow()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ =>
        {
            OnConfirmed?.Invoke();
            Close();
        };

        CloseButton.Visible = false;
    }
}
