## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:  # Frontier
  - ClothingEyesHudSecurity # Frontier
  - ForensicPad # Frontier
  - Handcuffs # Frontier
  - TargetClown # Frontier
  - TargetHuman # Frontier
  - TargetSyndicate # Frontier
  - Zipties # Frontier

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  # - WeaponFlareGunSecurity # Frontier

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - Wirecutter
  - MagazineRiotGunTearGas
  - MagazineRiotGunStinger
  - BaseMagazineRiotgun

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:  # Frontier
  - Flash # Frontier
  - Stunbaton # Frontier
  - CombatKnife # Frontier
  - RiotShield # Frontier

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - NFClothingBackpackElectropack # Frontier: use NF prefix
  - HoloprojectorSecurity # Frontier
  - NFPortableRecharger # Frontier: use NF prefix
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - NFTelescopicShield # Frontier: use NF prefix
  - EnergyDomeDirectionalTurtle #HL
  - ClothingBackpackTactical #HL
  - ClothingBackpackExplorer #HL
  - ClothingRucksack #HL

- type: latheRecipePack
  id: SecurityBoards
  # abstract: true # Frontier: finally, spammable shuttle guns
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - ExplosivePayload

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
    # Sandwich edit for _Mono ammo start
  - Magazine12_gaugeBeanbag
  - AmmoBox12_gaugeBeanbag 
  - AmmoBox12_gaugeTranquilizer
  - AmmoBox45_ACPRubber
  - Magazine45_ACPPistolRubber
  - Magazine45_ACPSubMachineGunRubber
  - AmmoBox45_magnumRubber
  - Magazine45_magnumPistolRubber
  - SpeedLoader45_magnumRubber
  - Magazine46x30mmPistolRubber
  - Magazine46x30mmSubMachineGunRubber
  - AmmoBox46x30mmRubber
  - AmmoBox556x45mmRubber
  - Magazine556x45mmRubber
  - SpeedLoader556x45mmRubber
  - AmmoBox57x28mmRubber
  - Magazine57x28mmPistolRubber
  - Magazine57x28mmSubMachineGunRubber
  - Magazine762x39mmRubber
  - AmmoBox762x39mmRubber
  - Magazine762x54mmRRubber
  - AmmoBox762x54mmRRubber
  - Magazine762x51mmRubber
  - AmmoBox762x51mmRubber
  - Magazine9x19mmPistolRubber
  - Magazine9x19mmSubMachineGunRubber
  - SpeedLoader9x19mmRubber
  - AmmoBox9x19mmRubber
    # Sandwich edit for _Mono ammo end

- type: latheRecipePack # Frontier
  id: SecurityWeapons # Frontier
  recipes: # Frontier
  - Truncheon # Frontier
  - WeaponAdvancedLaser # Frontier
  - WeaponLaserCannon # Frontier
  - WeaponLaserCarbine # Frontier
  - WeaponXrayCannon # Frontier
  - WeaponTemperatureGun # Frontier

- type: latheRecipePack # Frontier
  id: SecurityDisablers # Frontier
  recipes: # Frontier
  - WeaponDisabler # Frontier
  - WeaponDisablerSMG # Frontier
