- type: playTimeTracker
  id: JobInterdyne

- type: playTimeTracker
  id: JobInterdyneHead

- type: playTimeTracker
  id: JobCentralCommandDirectorate

- type: playTimeTracker
  id: JobCentComNavyman

- type: playTimeTracker
  id: JobBorgQuad