name: Build & Test Debug

on:
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    if: '!contains(github.actor, ''[bot]'') && github.event.pull_request.draft == false'
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: actions/checkout@v4.2.2

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Content.Tests
      shell: bash
      env:
        DOTNET_GCHeapHardLimit: 15032385536
      run: |
        (while true; do echo "Alive Check, OK! $(date -u +'%Y-%m-%dT%H:%M:%SZ')"; sleep 60; done) &
        keepalive_pid=$!
        dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0
        exit_code=$?
        kill "$keepalive_pid" || true
        wait "$keepalive_pid" 2>/dev/null || true
        exit "$exit_code"

    - name: Run Content.IntegrationTests
      shell: bash
      env:
        DOTNET_GCHeapHardLimit: 15032385536
      run: |
        (while true; do echo "Alive Check, OK! $(date -u +'%Y-%m-%dT%H:%M:%SZ')"; sleep 60; done) &
        keepalive_pid=$!
        DOTNET_gcServer=1 dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj --filter "FullyQualifiedName!~ShipyardTest" -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed
        exit_code=$?
        kill "$keepalive_pid" || true
        wait "$keepalive_pid" 2>/dev/null || true
        exit "$exit_code"
  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
